# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 10:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('share', '0001_initial'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, default='', upload_to='static/upload/alipay')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品价格')),
                ('pay_way', models.IntegerField(choices=[(0, '支付宝'), (1, '微信'), (2, '当面交易')])),
                ('info', models.CharField(max_length=200)),
                ('sell_times', models.IntegerField(default=1)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.File')),
            ],
            options={
                'ordering': ['create_time'],
                'verbose_name_plural': '商品',
                'verbose_name': '商品',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.IntegerField(choices=[(0, '等待支付'), (1, '交易完成'), (2, '投诉中'), (3, '交易取消')])),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Good')),
            ],
            options={
                'ordering': ['create_time'],
                'verbose_name_plural': '订单',
                'verbose_name': '订单',
            },
        ),
    ]
