# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-27 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Order')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='pay_pic',
            field=models.ImageField(blank=True, default='', upload_to='static/upload/alipay'),
        ),
    ]
