# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-03 08:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('remark_type', models.IntegerField(choices=[(0, '好评'), (1, '差评')])),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User')),
            ],
            options={
                'ordering': ['create_time'],
                'verbose_name': '商品评论',
                'verbose_name_plural': '商品评论',
            },
        ),
        migrations.AlterField(
            model_name='good',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='index.User', verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='order',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='index.User'),
        ),
        migrations.AddField(
            model_name='goodremark',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Good'),
        ),
    ]
