# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-02 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_marked',
            field=models.BooleanField(default=False),
        ),
    ]
