# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademark',
            name='aim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark_to', to='index.User'),
        ),
    ]
