# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-30 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20180630_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '等待支付'), (1, '等待卖家确认'), (2, '交易完成'), (3, '投诉中'), (4, '交易取消')]),
        ),
    ]
