# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-28 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_trade_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trade_Message',
            new_name='TradeMessage',
        ),
    ]
