# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-03 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20180703_0956'),
        ('market', '0003_auto_20180703_1016'),
    ]

    operations = [
    ]
