# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-27 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20180627_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.File'),
        ),
    ]
