# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-04 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_trademark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trademark',
            options={'ordering': ['create_time'], 'verbose_name': '交易评论', 'verbose_name_plural': '交易评论'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.IntegerField(choices=[(0, '支付问题'), (1, '其他')], default=0),
            preserve_default=False,
        ),
    ]
