# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-04 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_trademark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trademark',
            options={'ordering': ['create_time'], 'verbose_name': '交易评论', 'verbose_name_plural': '交易评论'},
        ),
    ]
