# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-27 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
        ('market', '0004_auto_20180627_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='good',
            name='sell_times',
            field=models.IntegerField(default=0),
        ),
    ]
