# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-27 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20180627_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='创建者'),
        ),
    ]
