# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-04 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20180704_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='good',
            new_name='order',
        ),
    ]
