# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-05 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20180704_1002'),
        ('market', '0007_auto_20180704_0943'),
    ]

    operations = [
    ]
