# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-06 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_merge_20180705_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, default='static/logo.png', upload_to='static/upload/alipay'),
        ),
    ]
