# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-06 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20180706_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='static/upload/alipay'),
        ),
    ]
