# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='parent_review',
        ),
    ]
