# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-29 05:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateField(default=datetime.datetime.now)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Review')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.User')),
            ],
            options={
                'verbose_name_plural': '评论回复表',
                'verbose_name': '评论回复表',
            },
        ),
    ]
