# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-30 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reviews',
            field=models.TextField(null=True),
        ),
    ]
