# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-04 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180704_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='beadmired_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='benotadmired_num',
            field=models.IntegerField(default=0),
        ),
    ]
