# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-06 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180704_1903'),
        ('share', '0001_initial'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admirelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isGood', models.BooleanField(default=True)),
                ('isFile', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Article')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.File')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User')),
            ],
            options={
                'verbose_name': '点赞表',
                'ordering': ['create_time'],
                'verbose_name_plural': '点赞表',
            },
        ),
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.RemoveField(
            model_name='selectp',
            name='city',
        ),
        migrations.RemoveField(
            model_name='selectp',
            name='province',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='SelectP',
        ),
    ]
