# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-09 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admirelog',
            name='fid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.File'),
        ),
        migrations.AddField(
            model_name='admirelog',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
    ]
