# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-25 08:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 6, 25, 8, 0, 14, 847240, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
