# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-29 03:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.CharField(max_length=1000)),
                ('have_read', models.BooleanField(default=False)),
                ('aim_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aim_user', to='index.User')),
            ],
            options={
                'verbose_name': '用户通知',
                'verbose_name_plural': '用户通知',
                'ordering': ['create_time'],
            },
        ),
    ]
