# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-06 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='static/logo.png', upload_to='static/upload/profile_photo'),
        ),
    ]
