# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-10 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180709_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='title',
            field=models.CharField(default='信息工程学院', max_length=30),
        ),
        migrations.AlterField(
            model_name='collegetype',
            name='title',
            field=models.CharField(default='工科', max_length=20),
        ),
    ]
