# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-06 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180706_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admirelog',
            name='aid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Article'),
        ),
        migrations.AlterField(
            model_name='admirelog',
            name='fid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.File'),
        ),
    ]
