# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-29 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='arg0',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='arg1',
            field=models.IntegerField(null=True),
        ),
    ]
