# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180625_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='good_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='static/upload/profile_photo'),
        ),
    ]
