# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-29 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180629_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['create_time'], 'verbose_name': '全局通知', 'verbose_name_plural': '全局通知'},
        ),
        migrations.AddField(
            model_name='notification',
            name='arg2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='arg3',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
