# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180626_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='', upload_to='static/upload/profile_photo'),
        ),
    ]
