# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180626_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alipay',
            field=models.ImageField(blank=True, default='', upload_to='static/upload/alipay'),
        ),
        migrations.AddField(
            model_name='user',
            name='bad_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='wechatpay',
            field=models.ImageField(blank=True, default='', upload_to='static/upload/wechatpay'),
        ),
    ]
