# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_colleges_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegetype',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
