# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-30 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180629_1046'),
        ('index', '0004_auto_20180629_0653'),
    ]

    operations = [
    ]
