# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-27 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=20)),
                ('fileType', models.CharField(max_length=20)),
                ('fileSize', models.IntegerField()),
                ('fileBeDown', models.IntegerField()),
                ('fileCreateTime', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='share/upload')),
            ],
            options={
                'verbose_name_plural': '文件',
                'verbose_name': '文件',
            },
        ),
        migrations.CreateModel(
            name='FileClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name_plural': '文件类型',
                'verbose_name': '文件类型',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='fileClassify',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.FileClassify'),
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
    ]
