# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-30 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_beadmired',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
