# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-28 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(help_text='类别名称', max_length=20)),
                ('c_father', models.IntegerField(default=0, help_text='父级类别ID', max_length=4)),
                ('c_hidden', models.BooleanField(default=0)),
            ],
        ),
    ]
