# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-30 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_file_file_beadmired'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_benotadmired',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
