# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-03 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_file_file_benotadmired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_beadmired',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_benotadmired',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_status',
            field=models.IntegerField(default=0),
        ),
    ]
