# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20180626_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='share/upload'),
        ),
    ]
